services:
  marus2_simulator:
    container_name: marus2_container
    image: marus2_docker:latest
    ipc: host
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/tmp/.Xauthority
      - ${HOME}/marus2_shared:/home/marus2_user/shared
      - /dev:/dev
    command: ["tail", "-f", "/dev/null"]

